/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options to control the parsing and babelify process. */
export interface BabelifyOptions {
  /** The file name to associate with the source (for error reporting) */
  fileName?: string
  /** The syntax to use: "typescript" (default) or "ecmascript" */
  syntax?: string
  /** Whether to treat the source as a module (default true) */
  isModule?: boolean
  /** ECMAScript version: "es3", "es5" (default), "es2015", "es2016", etc. */
  esVersion?: string
}
/**
 * Parse a JavaScript/TypeScript source and transform it into a Babel-compatible AST.
 *
 * This function exposes the same pipeline as in your bench test. It creates a new SWC compiler,
 * parses the source using the provided options, and then runs the Babelify conversion.
 *
 * # Parameters
 * - `source`: The source code to parse.
 * - `options`: An optional object to override default parameters (file name, syntax, module mode, and ECMAScript version).
 *
 * # Returns
 * A JSON string representing the Babelified AST.
 *
 * # Example (in JavaScript)
 * ```js
 * const { parseAndBabelify } = require("your-native-addon");
 * const source = "let a = 1;";
 * const opts = { file_name: "example.js", syntax: "typescript", is_module: true, es_version: "es5" };
 * const astJson = parseAndBabelify(source, opts);
 * console.log(astJson);
 * ```
 */
export declare function parseAndBabelify(source: string, options?: BabelifyOptions | undefined | null): any
