name: Test In Console

on: [pull_request]

jobs:
  test-in-console:
    runs-on: ghcr.io/puppeteer/puppeteer:latest
    concurrency:
      group: ${{ github.head_ref }}-test-in-console
      cancel-in-progress: true
    timeout-minutes: 60

    env:
      TEST_PACKAGES_EXCLUDE: stylus,roles
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      PUPPETEER_PRODUCT: chromium
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium

    steps:
      - uses: actions/checkout@v3
      - run: ./packages/test-in-console/run.sh