name: Test In Console

on: [pull_request]

jobs:
  test-in-console:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.head_ref }}-test-in-console
      cancel-in-progress: true
    timeout-minutes: 60

    env:
      TEST_PACKAGES_EXCLUDE: stylus,roles
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      PUPPETEER_PRODUCT: chromium
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
      URL: http://localhost:4096/
      METEOR_PACKAGE_DIRS: packages/deprecated

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - run: |
          sudo apt-get update && sudo apt-get install -yq libgconf-2-4

      - uses: actions/cache/restore@v4
        with:
          path: ./dev_bundle
          key: ${{ runner.os }}-${{ hashFiles('meteor') }}-dev-bundle

      - run: cat /etc/resolv.conf
      
      - run: |
          whereis firefox
          whereis chromium
          whereis google-chrome
          whereis chrome

      - run: ./packages/test-in-console/run.sh

      - if: ${{ always() }}
        uses: actions/cache/save@v4
        with:
          path: ./dev_bundle
          key: ${{ runner.os }}-${{ hashFiles('meteor') }}-dev-bundle
