name: Test In Console

on: [pull_request]

jobs:
  test-in-console:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-test-in-console
      cancel-in-progress: true
    timeout-minutes: 60

    env:
      TEST_PACKAGES_EXCLUDE: stylus,roles

    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libnspr4 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libgbm1 \
            libasound2 \
            libpango-1.0-0 \
            libcairo2 \
            g++-12

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            .meteor
            .babel-cache
            dev_bundle
          key: ${{ runner.os }}-node-${{ hashFiles('meteor', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: ./packages/test-in-console/run.sh